# Generated by Django 3.2.6 on 2021-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('uncategorised', 'uncategorised'), ('mobiles', 'mobiles'), ('cars', 'cars'), ('uncategorised', 'uncategorised')], default='uncategorised', max_length=100),
        ),
    ]
